### ISSUE TITLE
Change path of contest folder

### ISSUE THREAD

**Issue by anirudhakulkarni** [DrSchwad/FastOlympicCodingHook#1]
The problems files are always stored in some other path. It should be stored in a folder that I want.
How to change the destination folder?

**Comment by DrSchwad** [comment]
Can you kindly be more specific? Where are the tests being saved in? The tests are supposed to be saved in the same directory as your code file. I'd like to learn more details, since this could possibly be a bug.

And regarding changing the destination, you can't. This plugin is a small extension on `FastOlympicCoding` plugin and for that plugin to work, the tests and code file need to be in the same directory. So, I can't do much about it. But you can open an issue on that plugin's github repository if you wish.

**Comment by DrSchwad** [comment]
Since there hasn't been any follow-ups, I'm assuming you got your questions answered/issues resolved, so I'm closing this issue. But I'm still curious as to exactly where the files are being saved in your case. Let me know if you want it to be looked upon.
